branches:
  except:
    # These branches are used by Bors-NG and therefore, should not be build by Travis CI.
    # https://bors.tech/documentation/getting-started/
    - master.tmp
    - staging.tmp
    - trying.tmp

# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
    # https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
    # https://stackoverflow.com/a/28751112/434196
    - name: Test Python 2.7 and Android API 16
      language: android  # Python 2 testing
      sudo: false
      jdk: oraclejdk8
      env:
        global:
          - DX_HEAP_SIZE=2048
          # 16 is the fastest as per
          # https://medium.com/zendesk-engineering/speeding-up-android-builds-on-travis-ci-1bb4cdbd9c62
          - ANDROID_API_LEVEL=28
          - ANDROID_EMU_API_LEVEL=22
          - ANDROID_ABI=x86
          - QEMU_AUDIO_DRV=none  # Remove audio
          - ADB_INSTALL_TIMEOUT=20  # minutes (2 minutes by default)
      android:
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - android-$ANDROID_EMU_API_LEVEL
          # Specify at least one system image
          - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
      before_script:
        - pip install --user -r requirements.txt
        # Android setup
        - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
        # -noaudio is not supported by this version of the emulator
        - emulator -avd test -no-window -no-boot-anim &
        - android-wait-for-emulator
      script:
        - sleep 120
        - adb shell dumpsys wifi
        - adb shell locksettings set-pin 123456
